# Goal
nav_msgs/Path mission
---
# Result
geometry_msgs/Twist current_vel
int16 index_wp_reached
sensor_msgs/NavSatFix current_position
---
# Feedback
geometry_msgs/Twist current_vel
int16 index_wp_reached
sensor_msgs/NavSatFix current_position