# Goal
farmbot_interfaces/Waypoints initial_path
std_msgs/String controller
std_msgs/String robot_description
---
# Result
std_msgs/Bool success
builtin_interfaces/Duration time_it_took
---
#Feedback
std_msgs/Int16 state
std_msgs/String last_uuid
geometry_msgs/Pose pose
sensor_msgs/NavSatFix gps
geometry_msgs/Twist vel